from __future__ import annotations

TEXTUAL_CATEGORIES = {
    "text",
    "structured_text",
    "source_code",
    "notebook",
}

PLACEHOLDER_CATEGORIES = {
    "audio",
    "video",
    "image",
    "document",
    "spreadsheet",
    "presentation",
    "scientific_data",
    "cad_or_technical",
    "database",
    "email",
    "ebook",
    "font",
    "geospatial",
    "executable_or_binary",
    "disk_image_or_container",
    "compressed",
    "unknown",
}

SUPPORTED_CATEGORIES = TEXTUAL_CATEGORIES | PLACEHOLDER_CATEGORIES | {"archive"}

SOURCE_CODE_EXTENSIONS = {
    ".asm",
    ".bat",
    ".bash",
    ".c",
    ".cc",
    ".cmd",
    ".cpp",
    ".cs",
    ".css",
    ".fish",
    ".go",
    ".h",
    ".hpp",
    ".java",
    ".js",
    ".jsx",
    ".kt",
    ".lua",
    ".m",
    ".mm",
    ".php",
    ".pl",
    ".pm",
    ".ps1",
    ".py",
    ".r",
    ".rb",
    ".rs",
    ".scala",
    ".sh",
    ".sql",
    ".swift",
    ".ts",
    ".tsx",
    ".zsh",
}

EXTENSION_HINTS: dict[str, tuple[str, str]] = {
    ".txt": ("text", "TXT"),
    ".text": ("text", "TXT"),
    ".log": ("text", "Log"),
    ".md": ("structured_text", "Markdown"),
    ".markdown": ("structured_text", "Markdown"),
    ".rst": ("structured_text", "reStructuredText"),
    ".adoc": ("structured_text", "AsciiDoc"),
    ".html": ("structured_text", "HTML"),
    ".htm": ("structured_text", "HTML"),
    ".xml": ("structured_text", "XML"),
    ".json": ("structured_text", "JSON"),
    ".jsonl": ("structured_text", "JSON Lines"),
    ".yaml": ("structured_text", "YAML"),
    ".yml": ("structured_text", "YAML"),
    ".toml": ("structured_text", "TOML"),
    ".ini": ("structured_text", "INI"),
    ".csv": ("structured_text", "CSV"),
    ".tsv": ("structured_text", "TSV"),
    ".rtf": ("structured_text", "RTF"),
    ".pdf": ("document", "PDF"),
    ".docx": ("document", "DOCX"),
    ".doc": ("document", "DOC"),
    ".odt": ("document", "ODT"),
    ".pages": ("document", "Pages"),
    ".xlsx": ("spreadsheet", "XLSX"),
    ".xls": ("spreadsheet", "XLS"),
    ".ods": ("spreadsheet", "ODS"),
    ".numbers": ("spreadsheet", "Numbers"),
    ".pptx": ("presentation", "PPTX"),
    ".ppt": ("presentation", "PPT"),
    ".odp": ("presentation", "ODP"),
    ".key": ("presentation", "Keynote"),
    ".png": ("image", "PNG"),
    ".jpg": ("image", "JPEG"),
    ".jpeg": ("image", "JPEG"),
    ".tif": ("image", "TIFF"),
    ".tiff": ("image", "TIFF"),
    ".webp": ("image", "WebP"),
    ".gif": ("image", "GIF"),
    ".svg": ("image", "SVG"),
    ".heic": ("image", "HEIC"),
    ".bmp": ("image", "BMP"),
    ".avif": ("image", "AVIF"),
    ".wav": ("audio", "WAV"),
    ".mp3": ("audio", "MP3"),
    ".flac": ("audio", "FLAC"),
    ".ogg": ("audio", "OGG"),
    ".aac": ("audio", "AAC"),
    ".m4a": ("audio", "M4A"),
    ".midi": ("audio", "MIDI"),
    ".mid": ("audio", "MIDI"),
    ".mp4": ("video", "MP4"),
    ".m4v": ("video", "MP4"),
    ".mkv": ("video", "MKV"),
    ".avi": ("video", "AVI"),
    ".mov": ("video", "MOV"),
    ".webm": ("video", "WebM"),
    ".zip": ("archive", "ZIP"),
    ".tar": ("archive", "TAR"),
    ".tgz": ("archive", "TAR.GZ"),
    ".gz": ("compressed", "GZIP"),
    ".bz2": ("compressed", "BZIP2"),
    ".xz": ("compressed", "XZ"),
    ".7z": ("archive", "7Z"),
    ".rar": ("archive", "RAR"),
    ".eml": ("email", "EML"),
    ".msg": ("email", "MSG"),
    ".mbox": ("email", "MBOX"),
    ".epub": ("ebook", "EPUB"),
    ".mobi": ("ebook", "MOBI"),
    ".azw": ("ebook", "AZW"),
    ".azw3": ("ebook", "AZW3"),
    ".ipynb": ("notebook", "IPYNB"),
    ".sqlite": ("database", "SQLite"),
    ".sqlite3": ("database", "SQLite"),
    ".db": ("database", "SQLite/DB"),
    ".mdb": ("database", "Access MDB"),
    ".accdb": ("database", "Access ACCDB"),
    ".parquet": ("scientific_data", "Parquet"),
    ".h5": ("scientific_data", "HDF5"),
    ".hdf5": ("scientific_data", "HDF5"),
    ".nc": ("scientific_data", "NetCDF"),
    ".cdf": ("scientific_data", "NetCDF"),
    ".fits": ("scientific_data", "FITS"),
    ".fit": ("scientific_data", "FITS"),
    ".mat": ("scientific_data", "MATLAB MAT"),
    ".npy": ("scientific_data", "NumPy NPY"),
    ".npz": ("scientific_data", "NumPy NPZ"),
    ".geojson": ("geospatial", "GeoJSON"),
    ".kml": ("geospatial", "KML"),
    ".kmz": ("archive", "KMZ"),
    ".shp": ("geospatial", "Shapefile"),
    ".gpkg": ("geospatial", "GeoPackage"),
    ".dxf": ("cad_or_technical", "DXF"),
    ".dwg": ("cad_or_technical", "DWG"),
    ".ifc": ("cad_or_technical", "IFC"),
    ".ifczip": ("cad_or_technical", "IFCZIP"),
    ".step": ("cad_or_technical", "STEP"),
    ".stp": ("cad_or_technical", "STEP"),
    ".stl": ("cad_or_technical", "STL"),
    ".obj": ("cad_or_technical", "OBJ"),
    ".iges": ("cad_or_technical", "IGES"),
    ".igs": ("cad_or_technical", "IGES"),
    ".ttf": ("font", "TrueType"),
    ".otf": ("font", "OpenType"),
    ".woff": ("font", "WOFF"),
    ".woff2": ("font", "WOFF2"),
    ".exe": ("executable_or_binary", "Windows executable"),
    ".dll": ("executable_or_binary", "Windows shared library"),
    ".so": ("executable_or_binary", "Unix shared library"),
    ".dylib": ("executable_or_binary", "macOS shared library"),
    ".bin": ("executable_or_binary", "raw binary"),
    ".iso": ("disk_image_or_container", "ISO disk image"),
    ".dmg": ("disk_image_or_container", "DMG disk image"),
    ".vhd": ("disk_image_or_container", "VHD disk image"),
    ".qcow2": ("disk_image_or_container", "QCOW2 disk image"),
}

MIME_HINTS: dict[str, tuple[str, str]] = {
    "application/json": ("structured_text", "JSON"),
    "application/jsonl": ("structured_text", "JSON Lines"),
    "application/ndjson": ("structured_text", "JSON Lines"),
    "application/x-ndjson": ("structured_text", "JSON Lines"),
    "application/xml": ("structured_text", "XML"),
    "text/xml": ("structured_text", "XML"),
    "text/html": ("structured_text", "HTML"),
    "text/markdown": ("structured_text", "Markdown"),
    "text/csv": ("structured_text", "CSV"),
    "text/tab-separated-values": ("structured_text", "TSV"),
    "application/x-yaml": ("structured_text", "YAML"),
    "application/yaml": ("structured_text", "YAML"),
    "text/yaml": ("structured_text", "YAML"),
    "application/pdf": ("document", "PDF"),
    "application/rtf": ("structured_text", "RTF"),
    "text/rtf": ("structured_text", "RTF"),
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": ("document", "DOCX"),
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": ("spreadsheet", "XLSX"),
    "application/vnd.openxmlformats-officedocument.presentationml.presentation": ("presentation", "PPTX"),
    "image/png": ("image", "PNG"),
    "image/jpeg": ("image", "JPEG"),
    "image/tiff": ("image", "TIFF"),
    "image/webp": ("image", "WebP"),
    "image/gif": ("image", "GIF"),
    "image/svg+xml": ("image", "SVG"),
    "image/bmp": ("image", "BMP"),
    "image/vnd.dwg": ("cad_or_technical", "DWG"),
    "image/x-dwg": ("cad_or_technical", "DWG"),
    "image/vnd.dxf": ("cad_or_technical", "DXF"),
    "image/x-dxf": ("cad_or_technical", "DXF"),
    "application/acad": ("cad_or_technical", "DWG"),
    "application/x-acad": ("cad_or_technical", "DWG"),
    "application/autocad_dwg": ("cad_or_technical", "DWG"),
    "application/dwg": ("cad_or_technical", "DWG"),
    "application/x-dwg": ("cad_or_technical", "DWG"),
    "application/dxf": ("cad_or_technical", "DXF"),
    "application/x-dxf": ("cad_or_technical", "DXF"),
    "image/fits": ("scientific_data", "FITS"),
    "application/fits": ("scientific_data", "FITS"),
    "audio/wav": ("audio", "WAV"),
    "audio/x-wav": ("audio", "WAV"),
    "audio/mpeg": ("audio", "MP3"),
    "audio/flac": ("audio", "FLAC"),
    "audio/ogg": ("audio", "OGG"),
    "audio/aac": ("audio", "AAC"),
    "audio/midi": ("audio", "MIDI"),
    "video/mp4": ("video", "MP4"),
    "video/x-matroska": ("video", "MKV"),
    "video/x-msvideo": ("video", "AVI"),
    "video/quicktime": ("video", "MOV"),
    "video/webm": ("video", "WebM"),
    "application/zip": ("archive", "ZIP"),
    "application/x-tar": ("archive", "TAR"),
    "application/gzip": ("compressed", "GZIP"),
    "application/x-bzip2": ("compressed", "BZIP2"),
    "application/x-xz": ("compressed", "XZ"),
    "application/x-7z-compressed": ("archive", "7Z"),
    "application/vnd.rar": ("archive", "RAR"),
    "message/rfc822": ("email", "EML"),
    "application/epub+zip": ("ebook", "EPUB"),
    "application/vnd.sqlite3": ("database", "SQLite"),
    "application/x-sqlite3": ("database", "SQLite"),
    "application/x-hdf": ("scientific_data", "HDF5"),
    "application/vnd.apache.parquet": ("scientific_data", "Parquet"),
    "font/ttf": ("font", "TrueType"),
    "font/otf": ("font", "OpenType"),
    "font/woff": ("font", "WOFF"),
    "font/woff2": ("font", "WOFF2"),
    "application/x-executable": ("executable_or_binary", "Executable"),
    "application/x-sharedlib": ("executable_or_binary", "Shared library"),
    "application/octet-stream": ("executable_or_binary", "raw binary"),
}
